import type { StudentGroup } from "@/types/group";

export const studentGroups = [
  {
    id: "group-fpb-admin",
    name: "FP Básica - Servicios Administrativos",
    vocationalLevel: "FP Básica",
    professionalFamily: "Administración y Gestión",
    cycleName: "Servicios Administrativos",
    languageLevel: "A2-low",
    publisher: "Macmillan Education",
    grammarTopics: ["grammar-imperatives-procedures", "grammar-polite-requests"],
    vocabularySets: ["vocab-admin-orders"],
    scenarios: ["supplier-order-email"],
  },
  {
    id: "group-gm-commerce",
    name: "Grado Medio - Actividades Comerciales",
    vocationalLevel: "Grado Medio",
    professionalFamily: "Comercio y Marketing",
    cycleName: "Actividades Comerciales",
    languageLevel: "A2-high",
    publisher: "Burlington Professional Modules",
    grammarTopics: ["grammar-polite-requests", "grammar-past-simple-incident-reports"],
    vocabularySets: ["vocab-commerce-complaints"],
    scenarios: ["complaint-response"],
  },
  {
    id: "group-gm-it-smr",
    name: "Grado Medio - Sistemas Microinformáticos y Redes",
    vocationalLevel: "Grado Medio",
    professionalFamily: "Informática y Comunicaciones",
    cycleName: "Sistemas Microinformáticos y Redes",
    languageLevel: "B1-low",
    publisher: "Cambridge University Press",
    grammarTopics: [
      "grammar-imperatives-procedures",
      "grammar-first-conditional-troubleshooting",
    ],
    vocabularySets: ["vocab-it-helpdesk"],
    scenarios: ["helpdesk-password-reset"],
  },
  {
    id: "group-gs-tourism",
    name: "Grado Superior - Gestión de Alojamientos Turísticos",
    vocationalLevel: "Grado Superior",
    professionalFamily: "Hostelería y Turismo",
    cycleName: "Gestión de Alojamientos Turísticos",
    languageLevel: "B1",
    publisher: "Oxford Professional English",
    grammarTopics: ["grammar-polite-requests", "grammar-past-simple-incident-reports"],
    vocabularySets: ["vocab-hospitality-bookings"],
    scenarios: ["hotel-booking-confirmation"],
  },
  {
    id: "group-gm-personal-image",
    name: "Grado Medio - Peluquería y Cosmética Capilar",
    vocationalLevel: "Grado Medio",
    professionalFamily: "Imagen Personal",
    cycleName: "Peluquería y Cosmética Capilar",
    languageLevel: "A2",
    publisher: "Oxford University Press",
    grammarTopics: ["grammar-advice-should", "grammar-polite-requests"],
    vocabularySets: ["vocab-salon-appointments"],
    scenarios: ["salon-appointment"],
  },
] satisfies StudentGroup[];
