import type { TeachingResource } from "@/types/resource";

export const teachingResources = [
  {
    id: "resource-email-admin-supplier-order",
    title: "Email a proveedor para realizar un pedido",
    type: "worksheet",
    professionalFamily: "Administración y Gestión",
    vocationalLevel: "FP Básica",
    learningTrack: "foundation",
    supportLevel: "high",
    languageLevel: "A2-low",
    scenario: "supplier-order-email",
    skillFocus: ["writing", "vocabulary"],
    content:
      "Ficha guiada para completar y escribir un email breve de pedido de material de oficina, confirmar cantidades y preguntar por la fecha de entrega.",
    createdAt: "2026-05-26T10:00:00.000Z",
  },
  {
    id: "resource-commerce-complaint-response",
    title: "Respuesta a una queja de cliente",
    type: "reading",
    professionalFamily: "Comercio y Marketing",
    vocationalLevel: "Grado Medio",
    learningTrack: "professional",
    supportLevel: "medium",
    languageLevel: "A2-high",
    scenario: "complaint-response",
    skillFocus: ["reading", "writing", "customer-service"],
    content:
      "Intercambio de emails sobre un pedido retrasado, con preguntas de comprensión y una tarea breve de respuesta profesional.",
    createdAt: "2026-05-26T10:15:00.000Z",
  },
  {
    id: "resource-it-helpdesk-password-reset",
    title: "Llamada de soporte: restablecer contraseña",
    type: "listening",
    professionalFamily: "Informática y Comunicaciones",
    vocationalLevel: "Grado Medio",
    learningTrack: "professional",
    supportLevel: "medium",
    languageLevel: "B1-low",
    scenario: "helpdesk-password-reset",
    skillFocus: ["listening", "speaking", "vocabulary"],
    content:
      "Guion de escucha en el que un técnico comprueba datos, da instrucciones para restablecer una contraseña y confirma el acceso del usuario.",
    createdAt: "2026-05-26T10:30:00.000Z",
  },
  {
    id: "resource-hospitality-booking-exam",
    title: "Prueba breve: confirmación de reserva hotelera",
    type: "exam",
    professionalFamily: "Hostelería y Turismo",
    vocationalLevel: "Grado Superior",
    learningTrack: "professional",
    supportLevel: "low",
    languageLevel: "B1",
    scenario: "hotel-booking-confirmation",
    skillFocus: ["reading", "writing", "customer-service"],
    content:
      "Prueba breve sobre datos de reserva, peticiones educadas, información del huésped y redacción de un email de confirmación.",
    createdAt: "2026-05-26T10:45:00.000Z",
  },
  {
    id: "resource-salon-appointment-roleplay",
    title: "Cita de peluquería y preferencias del cliente",
    type: "worksheet",
    professionalFamily: "Imagen Personal",
    vocationalLevel: "Grado Medio",
    learningTrack: "professional",
    supportLevel: "medium",
    languageLevel: "A2",
    scenario: "salon-appointment",
    skillFocus: ["speaking", "customer-service", "vocabulary"],
    content:
      "Ficha de dramatización para reservar una cita de peluquería, preguntar preferencias y confirmar hora, servicio y precio.",
    createdAt: "2026-05-26T11:00:00.000Z",
  },
] satisfies TeachingResource[];
