import type { VocabularySet } from "@/types/vocabulary";

export const vocabularySets = [
  {
    id: "vocab-admin-orders",
    title: "Pedidos y proveedores",
    category: "supplier-communication",
    professionalFamily: "Administración y Gestión",
    scenario: "supplier-order-email",
    level: "A2-high",
    skillFocus: ["writing", "mediation", "vocabulary"],
    words: [
      "order",
      "supplier",
      "invoice",
      "delivery date",
      "quantity",
      "available stock",
      "purchase order",
    ],
  },
  {
    id: "vocab-commerce-complaints",
    title: "Quejas de clientes y soluciones",
    category: "customer-service",
    professionalFamily: "Comercio y Marketing",
    scenario: "complaint-response",
    level: "B1-low",
    skillFocus: ["writing", "customer-service", "vocabulary"],
    words: [
      "complaint",
      "refund",
      "replacement",
      "delay",
      "apologise",
      "customer experience",
      "follow-up",
    ],
  },
  {
    id: "vocab-it-helpdesk",
    title: "Soporte técnico y resolución de incidencias",
    category: "technical-support",
    professionalFamily: "Informática y Comunicaciones",
    scenario: "helpdesk-password-reset",
    level: "B1",
    skillFocus: ["listening", "speaking", "vocabulary"],
    words: [
      "password reset",
      "user account",
      "network connection",
      "error message",
      "backup",
      "restart",
      "support ticket",
    ],
  },
  {
    id: "vocab-hospitality-bookings",
    title: "Reservas e información de huéspedes",
    category: "hospitality-service",
    professionalFamily: "Hostelería y Turismo",
    scenario: "hotel-booking-confirmation",
    level: "A2",
    skillFocus: ["speaking", "writing", "customer-service"],
    words: [
      "booking",
      "guest",
      "check-in",
      "double room",
      "breakfast included",
      "arrival time",
      "cancellation policy",
    ],
  },
  {
    id: "vocab-salon-appointments",
    title: "Citas y servicios de peluquería",
    category: "salon-services",
    professionalFamily: "Imagen Personal",
    scenario: "salon-appointment",
    level: "A2-low",
    skillFocus: ["speaking", "customer-service", "vocabulary"],
    words: [
      "appointment",
      "haircut",
      "highlights",
      "blow-dry",
      "available slot",
      "hair treatment",
      "client preferences",
    ],
  },
] satisfies VocabularySet[];
